### PR TITLE
Improve Crossplane Doc Styling

### PR DESCRIPTION
**Pull request by shanecmiller23**
- Added new global color variables
- Applied new global colors to backgrounds, typography, navigations, components
- Update code block style and theming. Refactored for easier future color changing
- Improve Tips/Hints/etc structure and theming

### CODE REVIEW

**Comment by plumbis** [comment]
I like the new code color styles.

I'm not a huge fan of the link green.

The [hint boxes](https://64c993667a00440008d67fee--crossplane.netlify.app/contribute/features/#hints-and-alert-boxes) in dark mode don't really pop.

**Review by jbw976 — COMMENTED** [review]
very cool @shanecmiller23, thanks for taking a pass through this!! i'm mostly looking at dark mode as well...

* agree with @plumbis that the hint boxes don't pop or stand out very much - they seem to have lost their distinct header colors and left border highlight color that helped them stand out - see 2 screenshots for comparison:
Screenshot 2023-08-02 at 6 17 01 PM
Screenshot 2023-08-02 at 6 17 07 PM


* what do you think of the single backtick inline code boxes? the gray feels a bit muted on the background, maybe something with more contrast?
Screenshot 2023-08-02 at 6 10 56 PM
* any styling updates you want to make for the hidden/expandable boxes? @plumbis and i had been discussing those a bit in #480, maybe in scope for this PR too?

**Comment by shanecmiller23** [comment]
Screenshot 2023-08-02 at 10 46 05 PM
Screenshot 2023-08-02 at 10 46 20 PM

@jbw976 updated colors for better contrast

Yeah the expandable blocks are on my list to take a pass at. I was planning to do those in a subsequent PR, as I'd also like to take a look at typography, Tables, Tabs, some navigation elements, and other components. I'll see if it's straightforward enough to quickly follow-up with those blocks in this one, but I don't think it should be a blocker

**Review by jeanduplessis — APPROVED** [review]
Thank you for these updates @shanecmiller23 
After the recent contrast updates, I'm happy with how this looks. 
We can iterate on further enhancements.

**Pull request merged**
