### PR TITLE
Add style support for copy button highlighting

### LINKED ISSUE #346: Align clipboard icon with top line when {copy-lines="1"}
From the discussion in https://github.com/crossplane/docs/pull/337#discussion_r1096567786, it could be a nice user experience improvement to vertically align the copy to clipboard icon with the top line of a code block, when only the first line will be copied, i.e. when `{copy-lines="1"}`.

@plumbis also added in https://github.com/crossplane/docs/pull/337#issuecomment-1416814888:
> I'll take a look at mapping the copy icon with a visual indicator of the lines that will be copied.

### PR DESCRIPTION
**Pull request by plumbis**
This adds support to highlight the lines that will be copied when hovering over the clipboard icon. 

Examples:

Screenshot 2023-03-01 at 11 51 44 AM

Screenshot 2023-03-01 at 11 24 56 AM

Resolves #346

Signed-off-by: Pete Lumbis <pete@upbound.io>

### CODE REVIEW

**Comment by jeanduplessis** [comment]
@plumbis I couldn't find a block on the preview app where I could check this working? https://deploy-preview-372--crossplane.netlify.app/

**Comment by plumbis** [comment]
Weird, not working on the deploy preview, let me look into it and request a review when it's working.

**Comment by plumbis** [comment]
I forgot to commit the compiled JS. Confirmed it's working in the deploy preview

https://deploy-preview-372--crossplane.netlify.app/v1.11/getting-started/provider-aws/#install-the-crossplane-helm-chart

**Review by jeanduplessis — APPROVED** [review]
Approving after confirming the functionality works correctly.
We can make some UX improvements from a color contrast and spacing pov, but those can be made in follow-up iterations.

**Pull request merged**
