### PR TITLE
Update composition-functions.md

### PR DESCRIPTION
**Pull request by joebowbeer**
Fix several nits in the composition functions doc.

Also fixed a couple typos in the vale config file comments.

### CODE REVIEW

**Review by plumbis — APPROVED** [review]

**Comment by plumbis** [comment]
Let's wait for the 1.16 docs to publish in #773 before merging

**Comment by joebowbeer** [comment]
@plumbis PTAL - I improved wording to address a passive voice lint check

**Comment by joebowbeer** [comment]
Please overrule the lint check. It is not helping in this case.

**Comment by jbw976** [comment]
> Please overrule the lint check. It is not helping in this case.

This can be done within your changes as described in the contributing guide: https://docs.crossplane.io/contribute/vale/#ignore-vale-rules

want to give that a try with another commit @joebowbeer?

**Comment by joebowbeer** [comment]
@jbw976 PTAL - lint rule disabled

By the way, as an author and technical reviewer, I don't think I could function without passive voice.

I think Robert Delwood makes some good points in this article:

[There is No You in API: A Case for Passive Voice in API Documentation](https://robertdelwood.medium.com/there-is-no-you-in-api-856a63e8084e)

> Use active voice where it makes sense. But understand that passive voice isn’t a grammatical error; it’s a matter of style. It’s your friend when the thing receiving an action is the important part of the sentence — especially in scientific and legal contexts — when the performer of an action is unknown or in cases where the performer distracts or is irrelevant.

**Comment by jbw976** [comment]
Thanks @joebowbeer for both the contribution and the good article about passive voice! that was an interesting read. it's good to have the option to use passive voice when it makes more sense and it looks like there are a good number of those exceptions in this docs repo already.  the more writer/author inclined maintainers on this repo can consider if more relaxed rules would be better for a new default, but I have a feeling that keeping the default as is and allowing exceptions when needed is a reasonable compromise :)

**Pull request merged**
